#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text())


def replace_in_task_section(report: str, task_id: str, new_block: str) -> str:
    marker = f"### "
    task_header_pos = report.find(task_id)
    if task_header_pos == -1:
        return report
    section_start = report.rfind("### ", 0, task_header_pos)
    if section_start == -1:
        return report
    next_section = report.find("\n### ", task_header_pos)
    section_end = next_section if next_section != -1 else len(report)
    section = report[section_start:section_end]

    old_block = "\n".join(
        [
            "#### Candidate Outputs",
            "- Step 1 candidate output: TODO",
            "- Step 2 candidate output: TODO",
            "- Step 3 candidate output: TODO",
            "",
        ]
    )
    if old_block not in section:
        return report
    section = section.replace(old_block, new_block, 1)
    return report[:section_start] + section + report[section_end:]


def main() -> int:
    parser = argparse.ArgumentParser(description="Merge subagent candidate outputs into a validation report.")
    parser.add_argument("--report", required=True, help="Path to the markdown validation report")
    parser.add_argument("--manifest", required=True, help="Manifest generated by validate_task_dataset.py")
    parser.add_argument("--output", required=True, help="Reviewed report output path")
    args = parser.parse_args()

    report_path = Path(args.report).expanduser().resolve()
    manifest_path = Path(args.manifest).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()

    report = report_path.read_text()
    manifest = load_json(manifest_path)

    for group in manifest.get("groups", []):
        template_path = Path(group["subagent_output_template"])
        if not template_path.exists():
            continue
        payload = load_json(template_path)
        task_id = payload.get("target_task_id", group.get("task_id"))
        new_block = "\n".join(
            [
                "#### Candidate Outputs",
                f"- Step 1 candidate output: {payload.get('step1_candidate_output', 'TODO')}",
                f"- Step 2 candidate output: {payload.get('step2_candidate_output', 'TODO')}",
                f"- Step 3 candidate output: {payload.get('step3_candidate_output', 'TODO')}",
                "",
            ]
        )
        report = replace_in_task_section(report, task_id, new_block)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(report)
    print(f"wrote {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
